# Pipeline Tuning Constants
MAX_CONCURRENT_LLM_CALLS = 5
GROUNDING_CONFIDENCE_THRESHOLD = 0.5
LOW_CONFIDENCE_THRESHOLD = 0.7
MAX_RETRIES_SQL_VALIDATOR = 3
EMBEDDING_MODEL = "all-MiniLM-L6-v2"
CACHE_DIR = "schema_cache"
FEW_SHOT_TOP_K = 3
CANDIDATE_TOP_K = 15
DIALECT = "snowflake"
